services:
  frontend-app:
    container_name: frontend-app
    image: 'jcayllahua-frontend:1.0.0'
    build: ./frontend/
    ports:
      - '3000:3000'
    depends_on:
        - backend-app

  backend-app:
    container_name: backend-app
    image: 'jcayllahua-backend:1.0.0'
    build: ./backend/
    ports:
      - '8080:8080'
    environment:
        - 'DATASOURCE_URL=jdbc:postgresql://backend-db:5432/challenge_api'
        - 'DATABASE_USER=postgres'
        - 'DATABASE_PASSWORD=postgres'
    depends_on:
        - backend-db
  backend-db:
    container_name: backend-db
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
        - 'POSTGRES_USER=postgres'
        - 'POSTGRES_PASSWORD=postgres'
        - 'POSTGRES_DB=challenge_api'




